sefaria/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib import admin
from django.http import HttpResponseRedirect

from emailusernames.forms import EmailAuthenticationForm

from sefaria.forms import HTMLPasswordResetForm
from sefaria.settings import DOWN_FOR_MAINTENANCE

admin.autodiscover()

# Texts API
urlpatterns = patterns('reader.views',
    (r'^api/texts/versions/(?P<tref>.+)$', 'versions_api'),
    (r'^api/texts/parashat_hashavua$', 'parashat_hashavua_api'),
    (r'^api/texts/random?$', 'random_text_api'),
    (r'^api/texts/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'texts_api'),
    (r'^api/texts/(?P<tref>.+)$', 'texts_api'),
    (r'^api/index/?$', 'table_of_contents_api'),
    (r'^api/index/titles/?$', 'text_titles_api'),
    (r'^api/index/(?P<title>.+)$', 'index_api'),
    (r'^api/links/bare/(?P<book>.+)/(?P<cat>.+)$', 'bare_link_api'),
    (r'^api/links/(?P<link_id_or_ref>.*)$', 'links_api'),
    (r'^api/notes/(?P<note_id>.*)$', 'notes_api'),
    (r'^api/counts/links/(?P<cat1>.+)/(?P<cat2>.+)$', 'link_count_api'),
    (r'^api/counts/(?P<title>.+)$', 'counts_api'),
    (r'^api/preview/(?P<title>.+)$', 'text_preview_api'),
)

# Reviews API
urlpatterns += patterns('reader.views',
    (r'^api/reviews/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'reviews_api'),
    (r'^api/reviews/(?P<review_id>.+)$', 'reviews_api'),
)

# History API
urlpatterns += patterns('reader.views',
    (r'^api/history/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'texts_history_api'),
    (r'^api/history/(?P<tref>.+)$', 'texts_history_api'),
)

# Translation Request API
urlpatterns += patterns('reader.views',
    (r'^api/translation-request/(?P<tref>.+)$', 'translation_request_api'),
)

# Edit Locks API (temporary locks on segments during editing)
urlpatterns += patterns('reader.views',
    (r'^api/locks/set/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'set_lock_api'),
    (r'^api/locks/release/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'release_lock_api'),
    (r'^api/locks/check/(?P<tref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'check_lock_api'),
)

# Lock Text API (permament locking of an entire text)
urlpatterns += patterns('reader.views',
    (r'^api/locktext/(?P<title>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'lock_text_api'),
)

# Campaigns 
urlpatterns += patterns('reader.views',
    (r'^translate/(?P<tref>.+)$', 'translation_flow'),
    (r'^translation-requests/completed?', 'completed_translation_requests'),
    (r'^translation-requests/?', 'translation_requests'),
    (r'^contests/(?P<page>new-profiles-contest)$', 'serve_static'),
    (r'^contests/(?P<slug>.+)$', 'contest_splash'),
    (r'^mishnah-contest-2013/?$', lambda x: HttpResponseRedirect('/contests/mishnah-contest-2013')),
)

# Texts Add / Edit / Translate
urlpatterns += patterns('reader.views',
    (r'^edit/textinfo/(?P<title>.+)$', 'edit_text_info'),
    (r'^add/textinfo/(?P<new_title>.+)$', 'edit_text_info'),
    (r'^add/new/?$', 'edit_text'),
    (r'^add/(?P<ref>.+)$', 'edit_text'),
    (r'^translate/(?P<ref>.+)$', 'edit_text'),
    (r'^edit/(?P<ref>.+)/(?P<lang>\w\w)/(?P<version>.+)$', 'edit_text'),
)

# Texts Page
urlpatterns += patterns('reader.views',
    (r'^texts/?$', 'texts_list'),
)

# Search Page
urlpatterns += patterns('reader.views',
    (r'^search/?$', 'search'),
)

# Discussions Page
urlpatterns += patterns('reader.views',
    (r'^discussions/?$', 'discussions'),
)

# Discussions API
urlpatterns += patterns('reader.views',
    (r'^api/discussions/new$', 'new_discussion_api'),
)

# Dashboard Page
urlpatterns += patterns('reader.views',
    (r'^dashboard/?$', 'dashboard'),
)

# Source Sheets
urlpatterns += patterns('sheets.views',
    (r'^sheets/?$', 'sheets_list'),
    (r'^sheets/new/?$', 'new_sheet'),
    (r'^sheets/tags/?$', 'sheets_tags_list'),
    (r'^sheets/tags/(?P<tag>.+)$', 'sheets_tag'),
    (r'^sheets/(?P<type>(public|private|allz))/?$', 'sheets_list'),
    (r'^sheets/(?P<sheet_id>\d+)$', 'view_sheet'),
)

# Source Sheets API
urlpatterns += patterns('sheets.views',    
    (r'^api/sheets/?$', 'sheet_list_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/delete$', 'delete_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/add$', 'add_source_to_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/add_ref$', 'add_ref_to_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/copy_source$', 'copy_source_to_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/tags$', 'update_sheet_tags_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)$', 'sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/like$', 'like_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/unlike$', 'unlike_sheet_api'),
    (r'^api/sheets/(?P<sheet_id>\d+)/likers$', 'sheet_likers_api'),
    (r'^api/sheets/user/(?P<user_id>\d+)$', 'user_sheet_list_api'),
    (r'^api/sheets/modified/(?P<sheet_id>\d+)/(?P<timestamp>.+)$', 'check_sheet_modified_api'),

)

# Activity 
urlpatterns += patterns('reader.views',
    (r'^activity/?$', 'global_activity'),
    (r'^activity/(?P<page>\d+)$', 'global_activity'),
    (r'^activity/(?P<tref>[^/]+)/(?P<lang>.{2})/(?P<version>.+)$', 'segment_history'),
    (r'^api/revert/(?P<tref>[^/]+)/(?P<lang>.{2})/(?P<version>.+)/(?P<revision>\d+)$', 'revert_api'),
)

# Profiles & Settings
urlpatterns += patterns('reader.views',
    (r'^my/profile', 'my_profile'),
    (r'^profile/(?P<username>[^/]+)(/(?P<page>\d+))?$', 'user_profile'),
    (r'^contributors/(?P<username>[^/]+)(/(?P<page>\d+))?$', 'profile_redirect'),
    (r'^settings/account?$', 'account_settings'),
    (r'^settings/profile?$', 'edit_profile'),
    (r'^api/profile$', 'profile_api'),
)

# Random Text 
urlpatterns += patterns('reader.views',
    (r'^random/link$',        'random_redirect'),
    (r'^random/?$',           'random_text_page'),
)

# Notifications API
urlpatterns += patterns('reader.views',
    (r'^api/notifications/?$', 'notifications_api'),
    (r'^api/notifications/read', 'notifications_read_api'),
)

# Messages API
urlpatterns += patterns('reader.views',
    (r'^api/messages/?$', 'messages_api'),
)

# Following API
urlpatterns += patterns('reader.views',
    (r'^api/(?P<action>(follow|unfollow))/(?P<uid>\d+)$', 'follow_api'),
    (r'^api/(?P<kind>(followers|followees))/(?P<uid>\d+)$', 'follow_list_api'),

)

# Partners 
urlpatterns += patterns('sheets.views',
    (r'^partners/(?P<partner>.+)$', 'partner_page'),
)

# Registration
urlpatterns += patterns('',
    url(r'^login/?$', 'sefaria.views.login', {'authentication_form': EmailAuthenticationForm}, name='login'),
    url(r'^logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/', 'redirect_field_name': 'next'}, name='logout'),
    url(r'^register/?$', 'sefaria.views.register', name='register'),
    url(r'^password/reset/?$', 'django.contrib.auth.views.password_reset', {'password_reset_form': HTMLPasswordResetForm}, name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
)

# Static Content 
urlpatterns += patterns('reader.views', 
    url(r'^$', 'splash', name="home"),
    (r'^splash/?$', 'splash'),
    (r'^metrics/?$', 'metrics'),
    (r'^digitized-by-sefaria/?$', 'digitized_by_sefaria'),
    (r'^(donate|translation-guidelines|transliteration-guidelines|even-haezer-guidelines|related-projects|jobs|terms|privacy-policy|meetup1|meetup2|random-walk-through-torah|strategy|supporters)/?$', 'serve_static'),
)

# Explore
urlpatterns += patterns('reader.views',
    (r'^explore(/(?P<book1>[A-Za-z-]+))?(/(?P<book2>[A-Za-z-]+))?/(?P<lang>\w\w)/?$', 'explore'),
    (r'^explore(/(?P<book1>[A-Za-z-]+))?(/(?P<book2>[A-Za-z-]+))?/?$', 'explore')
)

# Redirect to Forum, Wiki
urlpatterns += patterns('',
    (r'^forum/?$', lambda x: HttpResponseRedirect('https://groups.google.com/forum/?fromgroups#!forum/sefaria')),
    (r'^wiki/?$', lambda x: HttpResponseRedirect('https://github.com/blockspeiser/Sefaria-Project/wiki')),
    (r'^educators/?$', lambda x: HttpResponseRedirect('https://github.com/blockspeiser/Sefaria-Project/wiki/Sefaria-for-Educators')),
    (r'^developers/?$', lambda x: HttpResponseRedirect('https://github.com/blockspeiser/Sefaria-Project/wiki#developers')),
    (r'^contribute/?$', lambda x: HttpResponseRedirect('https://github.com/blockspeiser/Sefaria-Project/wiki/Guide-to-Contributing')),
    (r'^faq/?$', lambda x: HttpResponseRedirect('https://github.com/blockspeiser/Sefaria-Project/wiki#frequently-asked-questions')),

)

# Email Subscribe 
urlpatterns += patterns('sefaria.views', 
    (r'^api/subscribe/(?P<email>.+)$', 'subscribe'),
)


# Admin 
urlpatterns += patterns('', 
    (r'^admin/reset/cache', 'sefaria.views.reset_cache'),
    #(r'^admin/view/template_cache/(?P<title>.+)$', 'sefaria.views.view_cached_elem'),
    #(r'^admin/delete/template_cache/(?P<title>.+)$', 'sefaria.views.del_cached_elem'),
    (r'^admin/rebuild/counts-toc', 'sefaria.views.rebuild_counts_and_toc'),
    (r'^admin/rebuild/counts', 'sefaria.views.reset_counts'),
    (r'^admin/rebuild/toc', 'sefaria.views.rebuild_toc'),
    (r'^admin/rebuild/commentary-links/(?P<title>.+)$', 'sefaria.views.rebuild_commentary_links'),
    (r'^admin/rebuild/citation-links/(?P<title>.+)$', 'sefaria.views.rebuild_citation_links'),
    (r'^admin/save/toc', 'sefaria.views.save_toc'),
    (r'^admin/cache/stats', 'sefaria.views.cache_stats'),
    (r'^admin/cache/dump', 'sefaria.views.cache_dump'),
    (r'^admin/export/all', 'sefaria.views.export_all'),
    (r'^admin/error', 'sefaria.views.cause_error'),
    (r'^admin/?', include(admin.site.urls)),
)

# Catch all to send to Reader
urlpatterns += patterns('reader.views', 

reader/models.py
from django.db import models

# Create your models here.

sheets/models.py
from django.db import models

# Create your models here.

sefaria/forms.py
"""
Override of Django forms for new users and password reset.

Includes logic for subscribing to mailing list on register and for 
"User Seeds" -- pre-creating accounts that may already be in a Group.
"""


from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import *
from emailusernames.forms import EmailUserCreationForm
from emailusernames.utils import get_user, user_exists
from sefaria.client.util import subscribe_to_announce

SEED_GROUP = "User Seeds"


class NewUserForm(EmailUserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    subscribe_announce = forms.BooleanField(label="Receive important announcements",  initial=True, required=False)
    
    class Meta:
        model = User
        fields = ("email",)
 
    def __init__(self, *args, **kwargs):
        super(EmailUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['password2']
        self.fields.keyOrder = ["email", "first_name", "last_name", "password1", "subscribe_announce"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if user_exists(email):
            user = get_user(email)
            if not user.groups.filter(name=SEED_GROUP).exists():
                raise forms.ValidationError("A user with that email already exists.")
        return email

    def save(self, commit=True):
        email = self.cleaned_data["email"]
        if user_exists(email):
            # A 'User Seed' existing for this email address. 
            user = get_user(email)
            user.set_password(self.cleaned_data["password1"])
            seed_group = Group.objects.get(name=SEED_GROUP)
            user.groups.remove(seed_group)
        else:
            user = super(NewUserForm, self).save(commit=False)
        
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
               
        if commit:
            user.save()
        if self.cleaned_data["subscribe_announce"]:
            try:
                subscribe_to_announce(user.email, first_name=user.first_name, last_name=user.last_name)
            except:
                pass
        return user


class HTMLPasswordResetForm(PasswordResetForm):
    def save(self, domain_override=None, email_template_name='registration/password_reset_email.html', subject_template_name='registration/pass_reset_subject.txt',
             use_https=False, token_generator=default_token_generator, from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the user
        """
        from django.core.mail import EmailMessage
        for user in self.users_cache:
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': int_to_base36(user.id),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': use_https and 'https' or 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            msg = EmailMessage(subject, email, from_email, [user.email])
            msg.content_subtype = "html"
            msg.send()

templates/account_settings.html
{% extends "base.html" %}

{% block content %}
<div id="accountSettingsContent">
	<h1>Sefaria Account Settings</h1>
	<br>
	<div id="emailNotifications" class="well">
		<h3>Send summary emails for unread notifications at most:</h3>
		<input type="radio" name="email_notifications" value="daily" {% if profile.settings.email_notifications == "daily" %}checked="checked"{% endif %}> Daily<br>
		<input type="radio" name="email_notifications" value="weekly" {% if profile.settings.email_notifications == "weekly" %}checked="checked"{% endif %}> Weekly<br>
		<input type="radio" name="email_notifications" value="never" {% if profile.settings.email_notifications == "never" %}checked="checked"{% endif %}> Never
	</div>
	<div id="saveAccountSettings" class="btn btn-primary">Save</div>
</div>
{% endblock %}

{% block js %}
	<script>
		$(function(){
			$("#saveAccountSettings").click(function(){
				var profile = {
						settings: {
							email_notifications: $("#emailNotifications input:checked").val()
						}
				};

				$.post("/api/profile", {json: JSON.stringify(profile)}, function(data) {
					if ("error" in data) {
						sjs.alert.message(data.error);
					} else {
						sjs.alert.message("Settings Saved.");
						sjs.track.event("Settings", "Email Notifications Change", $("#emailNotifications input:checked").val());
					}
				});
			});
		});
	</script>
{% endblock %}

templates/translate_campaign.html
{% extends "base.html" %}

{% load sefaria_tags %}
{% load humanize %}

{% block head %}
	<meta name="description" content="Help create the first free English translation of {{ base_ref }}. None currently exists, but with your help we can change that.">
{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}

<div id="translateCampaign" class="container">
	
	<div class="row">
		<div class="span10 offset1">
			<div id="about">

				{% if not thanks %}
					<h1>{{ title }}</h1>
					<p>You don't have to be an expert to help, this is just a first draft. Your contribution will be reviewed and edited by the Sefaria community. This text will be licensed under a <a href="http://creativecommons.org/publicdomain/zero/1.0/" target="_blank">Creative Commons Zero</a> license - free for anyone to use or reuse.</p> 
					<p id="askAFriendBox">
						<b>Can't translate Hebrew?</b>&nbsp;&nbsp;
						<span id="askSomeone">Ask a friend to help.</span>
						<div id="shareModal" class="modal">
							<h3>Tell your friends you want them help create a free English translation of {{ assigned.book }}</h3>
							<!-- AddThis Button BEGIN -->
							<div class="shareBox addthis_toolbox addthis_default_style addthis_32x32_style">
								<a class="addthis_button_facebook"></a>
								<a class="addthis_button_twitter"></a>
								<a class="addthis_button_google_plusone_share"></a>
								<a class="addthis_button_gmail"></a>
								<a class="addthis_button_email"></a>
								<input value="{{ request.build_absolute_uri }}">
							</div>
							<!-- AddThis Button END -->	
						</div>
					</p>
				{% else %}
					<h1>Thank you for Contributing!</h1>
					<p>This experiment will only work if we can achieve a critical mass.
						<br><b>Can you help spread the word?</b></p>
					<!-- AddThis Button BEGIN -->
					<div class="shareBox addthis_toolbox addthis_default_style addthis_32x32_style">
						<a class="addthis_button_facebook"></a>
						<a class="addthis_button_twitter"></a>
						<a class="addthis_button_google_plusone_share"></a>
						<a class="addthis_button_gmail"></a>
						<a class="addthis_button_email"></a>
						<input value="{{ request.build_absolute_uri }}">
					</div>
					<!-- AddThis Button END -->	
				{% endif %}

				<div class="graph text">
					<div class="graphInner">
						<div class="progressBar" style="width:{{ percent }}%">
							<span class="completeText">{{ percent|floatformat:0|intcomma }}% complete</span>
							<span class="remainingText">{{ remaining|intcomma }} {{ assigned_segment_name }}s of {{ assigned.book }} untranslated</span>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>


	<div class="row" id="transTitle">
		<div class="span6">
			<h2>Your assigment: {{ assigned_ref|ref_link }}</h2>
			Click words to open dictionary. <a href="/translate/{{ base_ref|url_safe }}?random=1{{ random_param }}">Get a different assignment.</a>
		</div>

		<div class="span6">
			<h2>Your translation:</h2>
			<br>
			Please review our <a href="/translation-guidelines">translation guidelines</a>.
		</div>

	</div>
	<div class="row" id="transBox">
		<div class="span6">
			<div id="original">
				{% autoescape off %}
					{{ assigned_text }}
				{% endautoescape %}
			</div>
		</div>

		<div class="span6">
			<textarea id="translation"></textarea>
		</div>
		<div class="clear"></div>
	</div>

	<div id="actions" class="row">
		<div class="span6 offset6">
		{% if user.email %}
			<div id="save" class="btn btn-primary btn-large">Save</div>
		{% else %}
			<div id="loginThenSave" class="btn btn-primary btn-large">Save</div>
		{% endif %}
		</div>
		<div class="clear"></div>
	</div>


	<div id="loginOrRegister" class="modal registrationContent">
		<h3>For quality assurance, please login or register to save your translation.</h3>
		<div id="login">
			<form method="post" action="/login">
				{% csrf_token %}
				<p>
					<label for="id_email">Email</label>
				    <input id="id_email" type="text" name="email" maxlength="75">
				</p>
				<p>
					<label for="id_password">Password</label>
				    <input type="password" name="password" id="id_password">
				</p>
				<button id="submitLogin" type="submit" class="btn btn-primary btn-large">
					Login
				</button>
				<a href="/password/reset" id="resetLink" target="_blank">
					Forgot your password?
				</a>
			</form>
		</div>
		<div id="register">
			<form action="/register" method="post">
				{% csrf_token %}
			    <p>
			    	<label for="id_email">Email:</label>
			    	<input id="id_email" type="text" name="email" maxlength="75">
			    </p>
				<p>
					<label for="id_first_name">First name:</label>
					<input type="text" name="first_name" id="id_first_name">
				</p>
				<p>
					<label for="id_last_name">Last name:</label>
					<input type="text" name="last_name" id="id_last_name">
				</p>
				<p>
					<label for="id_password1">Password:</label>
					<input type="password" name="password1" id="id_password1">
				</p>
				<p>
					<label for="id_subscribe_announce">Receive important announcements (no more than once a month):</label>
					<input checked="checked" type="checkbox" name="subscribe_announce" id="id_subscribe_announce">
				</p>
			    <input type="hidden" name="noredirect" value="true" />	   	
			    <button id="submitRegister" type="submit" class="btn btn-primary btn-large">
			    	Create Account
			    </button>
			  </form>
		</div>
	</div>

	<div id="timerModal" class="modal">
		<h2>Are you still working on this assignment?</h2>
		Continue working soon, or we may give this assignment to someone else.
		<div id="timer">
			<div class="clear"></div>
		</div>
		<div class="btn">Continue Working</div>
	</div> 

	<div id="overlay"></div>
</div>
{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/jquery-ui.min.js"></script>
<script src="/static/js/jquery.autosize.js"></script>
<script src="/static/js/util.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/jquery.countdown.css"> 
<script type="text/javascript" src="/static/js/jquery.countdown.js"></script>

<script>
{% autoescape off %}
	{% include "js/django-csrf.js" %}
{% endautoescape %}

$(function() {
	$("#translation").height($("#original").height())
		.autosize()
		.show()
		.focus();

	$("#askSomeone").click(function(){
		$("#shareModal").show().position({of: window});
		$("#overlay").show();
	});


	// Wrap all Hebrew words in links to a dictioary
	findAndReplaceDOMText(document.getElementById("original"), {
		find: /[^ .,;:()]+/g,
		wrap: "a"
	});
	$("#original a").each(function() {
		var word = $(this).text();
		$(this).attr("href", "http://www.morfix.co.il/" + word)
			.attr("target", "_blank");
	});

	$("#save").click(saveTranslation);

	$("#loginThenSave").click(showLoginOrRegister);

	$("#overlay").click(hideModals);

	$("#submitLogin").click(function(e) {
		e.preventDefault();
		var postData = $("#login form").serializeObject();
		// HACK - using AJAX to post to standard login page,
		// sifting through rendered HTML for error messages
		$.post("/login", postData, function(data) {
			var errors = $(data).find(".error").text();
			if (errors) {
				sjs.alert.message(errors, true);
			} else {
				sjs.track.event("Campaign", "Login", "");
				saveTranslation();
			}
		});
	});

	$("#submitRegister").click(function(e) {
		e.preventDefault();
		var postData = $("#register form").serializeObject();
		// HACK - using AJAX to post to standard register page,
		// sifting through rendered HTML for error messages
		$.post("/register", postData, function(data) {
			var errors = $(data).find(".errorlist").first().text();
			if (errors) {
				if (errors === "This field is required.") {
					errors = "All fields are required.";
				}
				sjs.alert.message(errors, true);
			} else {
				sjs.track.event("Campaign", "Regsiter", "");
				saveTranslation();
			}
		});
	});

	$(window).on("beforeunload", releaseLock);

	registerActivity();
	$("body").mousemove(registerActivity)
			 .keypress(registerActivity);
	sjs.renewInterval = setInterval(renewLock, 200000);
	sjs.checkInterval = setInterval(checkActivity, 100000);
});


var saveTranslation = function() {
	var text = $("#translation").val();
	if (!text) {
		sjs.alert.message("Please enter a translation first.")
		return;
	}
	var postUrl = "/api/texts/{{ assigned_ref_url }}";
	var postDict = {
		text: text,
		language: "en",
		versionTitle: "Sefaria Community Translation",
		versionSource: "http://www.sefaria.org"
	};
	var postJSON = JSON.stringify(postDict);

	sjs.alert.saving("Saving Translation...")
	$.post(postUrl, {json: postJSON}, function(data) {
		sjs.track.event("Campaign", "Save Click", "");
		if ("error" in data) {
			sjs.alert.message(data["error"]);
		} else {
			sjs.track.event("Campaign", "Successful Save", "");
			var next = "/translate/{{ base_ref|url_safe }}?thank=you";
			{% if next_text %}
			next += "&text={{ next_text|url_safe }}";
			{% elif next_section %}
			next += "&section={{ next_section }}";
			{% endif %}
			window.location = next;
		}
	});
};


var showLoginOrRegister = function() {
	var text = $("#translation").val();
	if (!text) {
		sjs.alert.message("Please enter a translation first.")
		return;
	}
	sjs.track.event("Campaign", "Show Login or Register", "");
	$("#overlay").show();
	$("#loginOrRegister").show().position({of: window});
};


var hideModals = function() {
	$("#overlay, .modal").hide();
};


var registerActivity = function() {
	sjs.lastActive = new Date();
};


var checkActivity = function() {
	var inactive = new Date() - sjs.lastActive;
	if (inactive > 300000 && !$("#timerModal").is(":visible")) {
		$("#timerModal, #overlay").show();
		$("#timerModal").position({of: window});
		$("#timer").countdown('destroy').countdown({
			until: +25*60,
			format: "MS",
			onExpiry: function() {
				releaseLock();
				hideModals();
				$("#save, #loginThenSave").remove();
				clearInterval(sjs.renewInterval);
				clearInterval(sjs.checkInterval);
				$(window).unbind("beforeunload");
				sjs.alert.message("Your assignment has timed out. Please reload this page to get a new assignment. To save any current work, please copy your translation to another window.");
				sjs.track.event("Campaign", "Assignment Timeout", "");
			}
		});
		$("#timerModal .btn").unbind().click(function(){
			$("#timerModal, #overlay").hide();
		});
	}
};

var renewLock = function() {
	var postUrl = "/api/locks/set/{{ assigned_ref_url }}/en/Sefaria_Community_Translation";
	$.post(postUrl);
};


var releaseLock = function() { 
	var postUrl = "/api/locks/release/{{ assigned_ref_url }}/en/Sefaria_Community_Translation";
	$.ajax({
	    type: 'POST',
	    async: false,
	    url: postUrl
	});
};
</script>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f0b68586603bc9f"></script>
{% endblock %}